disabled_rules:
  - object_literal
  - function_parameter_count
  - inert_defer
  - notification_center_detachment
  - shorthand_operator
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
excluded:
  - Pods
  - R.generated.swift
  - CosmosTests
  - CosmosUITests
  - Cosmos/Services/APIClient/Operations/Generated
  - Cosmos/Generated
  - Modules
  - vendor
file_length:
  warning: 500
  error: 700
type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 100
identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - ui
    - cg
    - id
large_tuple:
  warning: 3
  error: 5
line_length:
  warning: 400
  error: 700
  ignores_function_declarations: true
  ignores_comments: true
